server:
  port: 8090
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${POSTGRES_DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect